version: "3.9"
services:
  db:
    container_name: postgres_db
    image: postgres:14.13
    ports:
      - 5432:5432
    volumes:
      - db_vol:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Admin@123
      POSTGRES_DB: smart_utils

volumes:
  db_vol:
